version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATestForScafoldingTPPandMultiISProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQATestForScafoldingTPPandMultiISProject
  gitUsername: siqagituser
  gitBranch: main
